---
- name: AUTOMATED CHECK OF IOS VERSION, INTERFACES AND SET BUFFER SIZE
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
    - name: Gather L3 interfaces facts
      ios_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

    - name: display interface name
      debug:
        msg: "The L3 interface types are: {{ ansible_network_resources }}"

    - name: configure buffer size
      ios_logging:
        dest: buffered
        size: 5000

    - name: run command sh ip int br 
      ios_command:
        commands: show ip int br
      register: interfaces
  
    - name: display interfaces
      debug:
        var: interfaces["stdout_lines"][0]